#TMSH-VERSION: 15.1.0

sys global-settings {
    hostname bigip-dc2.example.local
}

ltm node /Common/10.2.1.10 {
    address 10.2.1.10
}

ltm pool /Common/pool_web_80 {
    load-balancing-mode round-robin
    members {
        /Common/10.2.1.10:80 {
            address 10.2.1.10
        }
    }
    monitor /Common/http
}

ltm virtual /Common/vs_web_443 {
    destination /Common/10.20.10.100:443
    ip-protocol tcp
    mask 255.255.255.255
    pool /Common/pool_web_80
    profiles {
        /Common/http { }
        /Common/clientssl {
            context clientside
        }
    }
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    vlans {
        /Common/vlan-external
    }
    vlans-enabled
    description "Portail web public - DC2 (secours)"
}

gtm server /Common/dc2_server {
    virtual-servers {
        /Common/vs_web_443 {
            destination 10.20.10.100:443
        }
    }
}
